name: stockpro
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  firebase_core:
  firebase_auth:
  cloud_firestore:
  google_sign_in:
  cloudinary_flutter: ^1.0.0
  cloudinary_url_gen: ^1.0.0
  # state management
  flutter_bloc:

  # routing
  auto_route:

  # networking
  retrofit:
  dio:

  # comparing dart objects
  equatable:

  # service locator
  get_it:

  fpdart:

  # core
  cached_network_image:
  intl:
  flutter_hooks:

  # ui
  shimmer: ^3.0.0
  flutter_svg:
  ionicons:
  image_picker: ^1.1.2
  flutter_typeahead: ^5.2.0
  flutter_launcher_icons: ^0.14.3
  loading_animation_widget: ^1.3.0
  convex_bottom_bar: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  floor_generator:
  retrofit_generator:
  build_runner:
  hive_generator:

  # rules and activating additional ones.
  flutter_lints:

flutter:
  uses-material-design: true

  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/muli/Muli.ttf
        - asset: assets/fonts/muli/Muli-Bold.ttf
          weight: 700
        - asset: assets/fonts/muli/Muli-Light.ttf
          weight: 300
